os: linux
language: python
python: "3.7"
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y mesa-common-dev

install:
  - pip install conan
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - cd sdl2
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest .
