os: linux
language: python
python: "3.7"
dist: xenial

compiler:
  - gcc

before_install:
  - sudo apt-get install -y build-essential libsdl2-dev libglu1-mesa-dev mesa-common-dev

install:
  - pip install conan
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - cd sdl2
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest .
