os: linux
language: python
python: "3.7"
dist: xenial

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7']
    env: COMPILER=g++-7
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['clang-6.0', 'g++-7']
    env: COMPILER=clang++-6.0

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y mesa-common-dev

install:
  - pip install conan
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - cd sdl2
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest .
